### ISSUE TITLE
(Wireframe) US0X - Tela Login

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-GaiaDex-FrontEnd#102]
# Descrição

Esta issue requer a implementação da Tela de login.
Nesta etapa (wireframe), requer-se apenas a entrega do layout responsivo da tela.

Segue imagem de referência ([para acessar o prototipo, clique aqui](https://www.figma.com/file/aZt1BiKEaVJilKd3aXWRcl/GaiaDex-Revamp?node-id=122%3A464)):

![screen_Sign In](https://user-images.githubusercontent.com/23236957/96403187-0de49d00-11ae-11eb-952b-3a66c920712b.png)

### Texto:Seja bem-vindo

```css
font-family: Inter;
font-style: normal;
font-weight: 600;
font-size: 2.76em;
line-height: 3.3em;
color: #F2E0F5;
```

### InputField:Seu email + Senha

```css
input[type=text],[type=password] {
  height: 8%;
  width:83%;
  margin-left: 8.5%;
  margin-right: 8.5%;
  background: rgba(36, 37, 40, 0.1);
  border-radius: 20px;
  border: transparent;
  font-family: Inter;
  font-style: normal;
  font-weight: 500;
  font-size: 1.08em;
  line-height: 100%;
  color: #3C3C3C;
}
```

#### Texto

```css
font-family: Inter;
font-style: normal;
font-weight: 600;
font-size: 1.92em;
line-height: 2.3em;
color: #242528;
```

##### circulo

```css
#circle {
    border-radius: 100%;
    width: 8.5vw;
    height: 8.5vw;
    background: #4D525A;
    }
```

##### Seta dentro do circulo

```html
<div id="circle">
    <svg width="24" height="15" viewBox="0 0 24 15" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M23.0993 6.93273L15.8993 0.171614C15.7118 -0.00447041 15.4081 -0.00447041 15.2206 0.171614C15.0331 0.347699 15.0331 0.632934 15.2206 0.808976L21.6012 6.80068H0.680026C0.414707 6.80068 0.200012 7.00228 0.200012 7.25143C0.200012 7.50058 0.414707 7.70219 0.680026 7.70219H21.6012L15.2206 13.6938C15.0331 13.8699 15.0331 14.1552 15.2206 14.3312C15.3143 14.4192 15.4372 14.4633 15.56 14.4633C15.6828 14.4633 15.8056 14.4192 15.8994 14.3312L23.0994 7.57009C23.2868 7.39405 23.2868 7.10881 23.0993 6.93273Z" fill="#F2E0F5"/>
    </svg>
</div>
```

#### Botão fb_google

```css
height: 6.20%;
width: 83%;
margin-left: 8.5%;
margin-right: 8.5%;
background: #38143E;
border: 0.95px solid #E15A97;
box-sizing: border-box;
border-radius: 10px;
```

#### Texto fb_google

```css
font-family: Inter;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 171%;
text-align: center;
letter-spacing: 0.1px;
color: #F2E0F5;
```

##### icone facebook

```html
<svg width="19" height="19" viewBox="0 0 19 19" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M2.88308 0C1.2908 0 0 1.2908 0 2.88308V16.1169C0 17.7092 1.2908 19 2.88308 19H16.1169C17.7092 19 19 17.7092 19 16.1169V2.88308C19 1.2908 17.7092 0 16.1169 0H2.88308ZM7.49323 18.8768V12.4407H4.52323V9.4113H7.49323V7.10239C7.49323 4.47612 9.23751 3.02545 11.9091 3.02545C13.1886 3.02545 14.5265 3.22997 14.5265 3.22997V5.80764H13.0523C11.5998 5.80764 11.1468 6.61559 11.1468 7.44424V9.4113H14.3893L13.8707 12.4407H11.1468V18.8768H7.49323Z" fill="#F2E0F5"/>
</svg>
```

##### icone google

```html
<svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M20.88 10.1677C20.88 15.8255 16.8769 19.852 10.9652 19.852C5.29731 19.852 0.720001 15.4217 0.720001 9.93576C0.720001 4.44985 5.29731 0.0195312 10.9652 0.0195312C13.7249 0.0195312 16.0466 0.999159 17.8353 2.61454L15.0468 5.20956C11.399 1.80285 4.61567 4.36188 4.61567 9.93576C4.61567 13.3944 7.4703 16.1974 10.9652 16.1974C15.022 16.1974 16.5423 13.3825 16.7819 11.923H10.9652V8.5123H20.7189C20.8139 9.02011 20.88 9.50792 20.88 10.1677Z" fill="#F2E0F5"/>
</svg>
```

#### conteudo

```css
font-family: Inter;
font-style: normal;
font-weight: 600;
font-size: 1.08em;
line-height: 100%;
display: flex;
align-items: center;
text-align: center;
color: #242528;
/* adorno */
box-shadow: inset 0 -0.5vw 0 white, inset 0 -1.2vw 0 #19BB53; /* #E15A97 */
```
